[project]
name = "voice-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiortc>=1.14.0",
    "fastapi[standard]>=0.136.1",
    "pipecat-ai-small-webrtc-prebuilt>=2.5.0",
    "pipecat-ai[cartesia,daily,deepgram,openai,silero,webrtc]>=1.2.1",
    "python-dotenv>=1.2.2",
]
